import Head from 'next/head'
import Layout from "../components/layout";
import {unsplash} from "../api/unsplash";
import styles from './home.module.css'
import {Basic} from "unsplash-js/dist/methods/photos/types";
import {ImageItem} from "../components/imageItem";

type TProps = {
  photos:  Basic[]
}

const Home = (props: TProps) => {
  return (
    <>
      <Head>
        <title>12 random photo in Unsplash.com</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Layout>
        <div className={styles.imagesContainer}>
          {
            props.photos.map((p: Basic) => (
              <div className={styles.image} key={p.id}>
                <ImageItem photo={p}/>
              </div>
            ))
          }
        </div>
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  const result = await unsplash.photos.getRandom({
    count: 12,
  });

  return {
    props: {
      photos: result.response || null
    }
  }
}

export default Home

